# Generated by Django 5.0.7 on 2024-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('antiques', 'Antiques'), ('renovation&repair', 'Renovation & repair'), ('artworks', 'Artworks'), ('tools', 'Tools'), ('construction', 'Construction'), ('other', 'Other')], default='normal', max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.category'),
        ),
    ]
