# Generated by Django 5.0.7 on 2024-08-15 06:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_profile_azwy8y.jpg', max_length=255, verbose_name='image'),
        ),
    ]
