# Generated by Django 5.0.7 on 2024-10-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_view',
            field=models.BooleanField(default=True),
        ),
    ]
