# Generated by Django 5.0.7 on 2024-10-07 21:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
