# Generated by Django 5.0.7 on 2024-10-08 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_alter_advertisement_options_advertisement_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='professionals.advertisement'),
        ),
    ]
