# Generated by Django 5.0.7 on 2024-10-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_joboffer_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
